package com.javascript.jscript.Programs;

public class BasicProgramsCodes {

    //basics programs codes
    public static final String basic = "// program where the user has to guess a number generated by a program\n" +
            "\n" +
            "function guessNumber() {\n" +
            "\n" +
            "    // generating a random integer from 1 to 10\n" +
            "    const random = Math.floor(Math.random() * 10) + 1;\n" +
            "\n" +
            "    // take input from the user\n" +
            "    let number = parseInt(prompt('Guess a number from 1 to 10: '));\n" +
            "\n" +
            "    // take the input until the guess is correct\n" +
            "    while(number !== random) {\n" +
            "        number = parseInt(prompt('Guess a number from 1 to 10: '));\n" +
            "    }\n" +
            "\n" +
            "    // check if the guess is correct\n" +
            "    if(number == random) {\n" +
            "        console.log('You guessed the correct number.');\n" +
            "    }\n" +
            "\n" +
            "  }\n" +
            "\n" +
            "// call the function\n" +
            "guessNumber();";

    public static final String basic1 ="// program to find the sum of natural numbers using recursion\n" +
            "\n" +
            "function sum(num) {\n" +
            "    if(num > 0) {\n" +
            "        return num + sum(num - 1);\n" +
            "    }\n" +
            "    else {\n" +
            "        return num;\n" +
            "    }\n" +
            " }\n" +
            "\n" +
            "// take input from the user\n" +
            "const number = parseInt(prompt('Enter a positive integer: '));\n" +
            "\n" +
            "const result = sum(number);\n" +
            "\n" +
            "// display the result\n" +
            "console.log(`The sum is ${result}`);";
    public static final String basic2 ="// program to shuffle the deck of cards\n" +
            "\n" +
            "// declare card elements\n" +
            "const suits = [\"Spades\", \"Diamonds\", \"Club\", \"Heart\"];\n" +
            "const values = [\n" +
            "  \"Ace\",\n" +
            "  \"2\",\n" +
            "  \"3\",\n" +
            "  \"4\",\n" +
            "  \"5\",\n" +
            "  \"6\",\n" +
            "  \"7\",\n" +
            "  \"8\",\n" +
            "  \"9\",\n" +
            "  \"10\",\n" +
            "  \"Jack\",\n" +
            "  \"Queen\",\n" +
            "  \"King\",\n" +
            "];\n" +
            "\n" +
            "// empty array to contain cards\n" +
            "let deck = [];\n" +
            "\n" +
            "// create a deck of cards\n" +
            "for (let i = 0; i < suits.length; i++) {\n" +
            "    for (let x = 0; x < values.length; x++) {\n" +
            "        let card = { Value: values[x], Suit: suits[i] };\n" +
            "        deck.push(card);\n" +
            "    }\n" +
            "}\n" +
            "\n" +
            "// shuffle the cards\n" +
            "for (let i = deck.length - 1; i > 0; i--) {\n" +
            "    let j = Math.floor(Math.random() * i);\n" +
            "    let temp = deck[i];\n" +
            "    deck[i] = deck[j];\n" +
            "    deck[j] = temp;\n" +
            "}\n" +
            "\n" +
            "console.log('The first five cards are:');\n" +
            "\n" +
            "// display 5 results\n" +
            "for (let i = 0; i < 5; i++) {\n" +
            "    console.log(`${deck[i].Value} of ${deck[i].Suit}`)\n" +
            "}";
    public static final String advanced ="// program to create JavaScript object using object literal\n" +
            "const person = { \n" +
            "    name: 'John',\n" +
            "    age: 20,\n" +
            "    hobbies: ['reading', 'games', 'coding'],\n" +
            "    greet: function() {\n" +
            "        console.log('Hello everyone.');\n" +
            "    },\n" +
            "    score: {\n" +
            "        maths: 90,\n" +
            "        science: 80\n" +
            "    }\n" +
            "};\n" +
            "\n" +
            "console.log(typeof person); // object\n" +
            "\n" +
            "// accessing the object value\n" +
            "console.log(person.name);\n" +
            "console.log(person.hobbies[0]);\n" +
            "person.greet();\n" +
            "console.log(person.score.maths);";
    public static final String advanced2 ="// program to count the number of vowels in a string\n" +
            "\n" +
            "function countVowel(str) { \n" +
            "\n" +
            "    // find the count of vowels\n" +
            "    const count = str.match(/[aeiou]/gi).length;\n" +
            "\n" +
            "    // return number of vowels\n" +
            "    return count;\n" +
            "}\n" +
            "\n" +
            "// take input\n" +
            "const string = prompt('Enter a string: ');\n" +
            "\n" +
            "const result = countVowel(string);\n" +
            "\n" +
            "console.log(result);";
    public static final String expert ="// program to remove a property from an object\n" +
            "\n" +
            "// creating an object\n" +
            "const student = { \n" +
            "    name: 'John',\n" +
            "    age: 20,\n" +
            "    hobbies: ['reading', 'games', 'coding'],\n" +
            "    greet: function() {\n" +
            "        console.log('Hello everyone.');\n" +
            "    },\n" +
            "    score: {\n" +
            "        maths: 90,\n" +
            "        science: 80\n" +
            "    }\n" +
            "};\n" +
            "\n" +
            "// deleting a property from an object\n" +
            "delete student.greet;\n" +
            "delete student['score'];\n" +
            "\n" +
            "console.log(student);";



    //basic programs outputs

    public static final String basicOutput1 ="" +
            "Enter the number: 9 \n" +
            "The square root of 9 is 3";

    public static final String basicOutput2 ="" +
            "The square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaNThe square root of 2.25 is 1.5\\n\" +\n" +
            "            \"    The square root of -4 is NaN\\n\" +\n" +
            "            \"    The square root of hello is NaN"
            ;


}

